server:
  port: "8080"
spring:
  application:
    name: "spring-init-production"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/app_db"
    username: "app_user"
    password: "app_password"
  jpa:
    hibernate:
      ddl-auto: "none"