server:
  port: "8080"
spring:
  application:
    name: "spring-init-production"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/app_db"
    username: "app_user"
    password: "app_password"
  jpa:
    hibernate:
      ddl-auto: "none"