name: spring-init-project
services:
  - name: backend
    github:
      repo: devcambo/spring-init-project
      branch: main
    source_dir: /
    http_port: 8080
    run_command: "java -jar target/spring-init-0.0.1-SNAPSHOT.jar"
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod